"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ClockPlus, Play, Square, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { ApiError } from "@/lib/api/client";
import { overtimeService } from "@/services/overtime-service";

function localInput(date: Date) { return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
function hm(minutes: number) { return `${Math.floor(minutes / 60)}g ${minutes % 60}p`; }
export function OvertimeManager() {
  const [now] = useState(() => new Date()); const start = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`; const end = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;
  const [type, setType] = useState<"weekday" | "weekend" | "holiday">("weekday"); const [multiplier, setMultiplier] = useState(1.5);
  const [manualStart, setManualStart] = useState(() => localInput(new Date(Date.now() - 60 * 60_000))); const [manualEnd, setManualEnd] = useState(() => localInput(new Date()));
  const client = useQueryClient(); const active = useQuery({ queryKey: ["overtime", "active"], queryFn: overtimeService.active, refetchInterval: 60_000 });
  const list = useQuery({ queryKey: ["overtime", start, end], queryFn: () => overtimeService.list(start, end) }); const summary = useQuery({ queryKey: ["overtime", "summary", start, end], queryFn: () => overtimeService.summary(start, end) });
  const refresh = async () => { await client.invalidateQueries({ queryKey: ["overtime"] }); };
  const action = useMutation({ mutationFn: (name: "start" | "end") => name === "start" ? overtimeService.start(type, multiplier) : overtimeService.end(), onSuccess: async (_, name) => { toast.success(name === "start" ? "Đã bắt đầu làm thêm" : "Đã kết thúc làm thêm"); await refresh(); }, onError: (e) => toast.error(e instanceof ApiError ? e.message : "Không thể cập nhật") });
  const create = useMutation({ mutationFn: () => overtimeService.create({ startedAt: new Date(manualStart).toISOString(), endedAt: new Date(manualEnd).toISOString(), overtimeType: type, multiplier, note: null }), onSuccess: async () => { toast.success("Đã thêm giờ làm thêm"); await refresh(); }, onError: (e) => toast.error(e instanceof ApiError ? e.message : "Không thể lưu") });
  const remove = useMutation({ mutationFn: overtimeService.remove, onSuccess: refresh });
  return <main className="mx-auto min-h-svh w-full max-w-5xl px-4 py-6 sm:px-6"><header className="mb-6 flex items-center gap-3"><Button asChild variant="ghost" size="icon"><Link href="/dashboard"><ArrowLeft /></Link></Button><div><h1 className="text-xl font-semibold">Làm thêm giờ</h1><p className="text-sm text-muted-foreground">Theo dõi thời gian và hệ số</p></div></header>
    <section className="grid gap-4 sm:grid-cols-3"><Stat label="Tổng tháng" value={summary.data ? hm(summary.data.totalMinutes) : "--"} /><Stat label="Giờ quy đổi" value={summary.data ? hm(Math.round(summary.data.weightedMinutes)) : "--"} /><Stat label="Số phiên" value={String(summary.data?.count ?? 0)} /></section>
    <section className="mt-4 grid gap-4 lg:grid-cols-2"><Card className="border-status-overtime/30 bg-status-overtime/5"><CardHeader><CardTitle className="flex items-center gap-2"><ClockPlus className="text-status-overtime" /> Bộ đếm làm thêm</CardTitle><CardDescription>{active.data ? `Bắt đầu lúc ${new Date(active.data.startedAt).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })}` : "Chưa có phiên đang chạy"}</CardDescription></CardHeader><CardContent className="space-y-4"><Rule type={type} setType={setType} multiplier={multiplier} setMultiplier={setMultiplier} />{active.isPending ? <Skeleton className="h-10" /> : active.data ? <Button size="lg" variant="destructive" onClick={() => action.mutate("end")} disabled={action.isPending}><Square /> Kết thúc</Button> : <Button size="lg" onClick={() => action.mutate("start")} disabled={action.isPending}><Play /> Bắt đầu làm thêm</Button>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Thêm thủ công</CardTitle><CardDescription>Dùng khi đã hoàn thành ca làm thêm.</CardDescription></CardHeader><CardContent className="space-y-4"><Rule type={type} setType={setType} multiplier={multiplier} setMultiplier={setMultiplier} /><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Bắt đầu</Label><Input type="datetime-local" value={manualStart} onChange={(e) => setManualStart(e.target.value)} /></div><div className="space-y-2"><Label>Kết thúc</Label><Input type="datetime-local" value={manualEnd} onChange={(e) => setManualEnd(e.target.value)} /></div></div><Button onClick={() => create.mutate()} disabled={create.isPending || new Date(manualEnd) <= new Date(manualStart)}>Lưu bản ghi</Button></CardContent></Card></section>
    <Card className="mt-4"><CardHeader><CardTitle>Lịch sử tháng</CardTitle></CardHeader><CardContent>{list.isPending ? <Skeleton className="h-24" /> : !list.data?.length ? <p className="py-8 text-center text-sm text-muted-foreground">Chưa có giờ làm thêm.</p> : <div className="space-y-2">{list.data.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="font-medium">{new Date(item.startedAt).toLocaleDateString("vi-VN")} · {hm(item.minutes ?? 0)}</p><p className="text-sm text-muted-foreground">{item.overtimeType} · hệ số {item.multiplier}</p></div><Button variant="ghost" size="icon" onClick={() => { if (confirm("Xoá phiên làm thêm này?")) remove.mutate(item.id); }}><Trash2 className="text-destructive" /></Button></div>)}</div>}</CardContent></Card>
  </main>;
}
function Rule({ type, setType, multiplier, setMultiplier }: { type: string; setType: (v: "weekday" | "weekend" | "holiday") => void; multiplier: number; setMultiplier: (v: number) => void }) { return <div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Loại ngày</Label><Select value={type} onValueChange={(v) => setType(v as "weekday" | "weekend" | "holiday")}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="weekday">Ngày thường</SelectItem><SelectItem value="weekend">Cuối tuần</SelectItem><SelectItem value="holiday">Ngày lễ</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Hệ số</Label><Select value={String(multiplier)} onValueChange={(v) => setMultiplier(Number(v))}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="1.5">150%</SelectItem><SelectItem value="2">200%</SelectItem><SelectItem value="3">300%</SelectItem></SelectContent></Select></div></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <Card size="sm"><CardContent><p className="text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></CardContent></Card>; }
