import type { Pool, PoolClient } from "pg";
import type { JournalInput, ProjectInput, TaskInput } from "../../application/validators/productivity-schemas.js";
export interface ProjectRow { id:string; name:string; color:string; description:string|null; is_archived:boolean; }
export interface TaskRow { id:string; project_id:string|null; project_name:string|null; project_color:string|null; title:string; description:string|null; task_date:string; priority:"low"|"medium"|"high"; status:"pending"|"in_progress"|"completed"|"cancelled"; estimated_minutes:number|null; tracked_minutes:number; active_timer_id:string|null; completed_at:Date|null; }
export class ProductivityRepository {
  static async projects(db:Pool,userId:string){ return (await db.query<ProjectRow>(`SELECT id,name,color,description,is_archived FROM projects WHERE user_id=$1 ORDER BY is_archived,name`,[userId])).rows; }
  static async createProject(db:Pool,userId:string,i:ProjectInput){ return (await db.query<ProjectRow>(`INSERT INTO projects(user_id,name,color,description,is_archived) VALUES($1,$2,$3,$4,$5) RETURNING id,name,color,description,is_archived`,[userId,i.name,i.color,i.description??null,i.isArchived])).rows[0]!; }
  static async updateProject(db:Pool,userId:string,id:string,i:ProjectInput){ return (await db.query<ProjectRow>(`UPDATE projects SET name=$3,color=$4,description=$5,is_archived=$6 WHERE user_id=$1 AND id=$2 RETURNING id,name,color,description,is_archived`,[userId,id,i.name,i.color,i.description??null,i.isArchived])).rows[0]??null; }
  static async deleteProject(db:Pool,userId:string,id:string){ return (await db.query(`DELETE FROM projects WHERE user_id=$1 AND id=$2`,[userId,id])).rowCount===1; }
  static async tasks(db:Pool,userId:string,q:{date?:string;projectId?:string;status?:string}){ return (await db.query<TaskRow>(`SELECT t.id,t.project_id,p.name project_name,p.color project_color,t.title,t.description,t.task_date::text,t.priority,t.status,t.estimated_minutes,t.completed_at,COALESCE(SUM(EXTRACT(EPOCH FROM(COALESCE(te.ended_at,NOW())-te.started_at))/60),0)::int tracked_minutes,MAX(te.id::text) FILTER(WHERE te.ended_at IS NULL) active_timer_id FROM tasks t LEFT JOIN projects p ON p.id=t.project_id LEFT JOIN task_time_entries te ON te.task_id=t.id WHERE t.user_id=$1 AND ($2::date IS NULL OR t.task_date=$2) AND ($3::uuid IS NULL OR t.project_id=$3) AND ($4::text IS NULL OR t.status=$4) GROUP BY t.id,p.id ORDER BY CASE t.priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,t.created_at`,[userId,q.date??null,q.projectId??null,q.status??null])).rows; }
  static async verifyProject(db:Pool|PoolClient,userId:string,id:string|null|undefined){ if(!id)return true; return (await db.query(`SELECT 1 FROM projects WHERE user_id=$1 AND id=$2`,[userId,id])).rowCount===1; }
  static async createTask(db:Pool,userId:string,i:TaskInput){ const id=(await db.query<{id:string}>(`INSERT INTO tasks(user_id,project_id,title,description,task_date,priority,estimated_minutes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id`,[userId,i.projectId??null,i.title,i.description??null,i.taskDate,i.priority,i.estimatedMinutes??null])).rows[0]!.id; return id; }
  static async updateTask(db:Pool,userId:string,id:string,i:TaskInput){ return (await db.query(`UPDATE tasks SET project_id=$3,title=$4,description=$5,task_date=$6,priority=$7,estimated_minutes=$8 WHERE user_id=$1 AND id=$2`,[userId,id,i.projectId??null,i.title,i.description??null,i.taskDate,i.priority,i.estimatedMinutes??null])).rowCount===1; }
  static async deleteTask(db:Pool,userId:string,id:string){return(await db.query(`DELETE FROM tasks WHERE user_id=$1 AND id=$2`,[userId,id])).rowCount===1;}
  static async complete(db:Pool,userId:string,id:string){return(await db.query(`UPDATE tasks SET status='completed',completed_at=NOW() WHERE user_id=$1 AND id=$2 RETURNING id`,[userId,id])).rowCount===1;}
  static async startTimer(db:PoolClient,userId:string,taskId:string,entryType:"timer"|"pomodoro"="timer"){const own=await db.query(`SELECT 1 FROM tasks WHERE user_id=$1 AND id=$2 FOR UPDATE`,[userId,taskId]);if(!own.rowCount)return null;const result=await db.query<{id:string;started_at:Date}>(`INSERT INTO task_time_entries(user_id,task_id,entry_type,started_at) VALUES($1,$2,$3,NOW()) RETURNING id,started_at`,[userId,taskId,entryType]);await db.query(`UPDATE tasks SET status='in_progress' WHERE id=$1`,[taskId]);return result.rows[0]!;}
  static async stopTimer(db:PoolClient,userId:string,taskId:string){return(await db.query<{id:string;started_at:Date;ended_at:Date}>(`UPDATE task_time_entries te SET ended_at=NOW() FROM tasks t WHERE te.task_id=t.id AND t.id=$2 AND t.user_id=$1 AND te.ended_at IS NULL RETURNING te.id,te.started_at,te.ended_at`,[userId,taskId])).rows[0]??null;}
  static async journals(db:Pool,userId:string,start:string,end:string){return(await db.query(`SELECT id,note_date::text,work_summary,next_day_plan,productivity_score FROM daily_notes WHERE user_id=$1 AND note_date BETWEEN $2 AND $3 ORDER BY note_date DESC`,[userId,start,end])).rows;}
  static async upsertJournal(db:Pool,userId:string,i:JournalInput){return(await db.query(`INSERT INTO daily_notes(user_id,note_date,work_summary,next_day_plan,productivity_score) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id,note_date) DO UPDATE SET work_summary=EXCLUDED.work_summary,next_day_plan=EXCLUDED.next_day_plan,productivity_score=EXCLUDED.productivity_score RETURNING id,note_date::text,work_summary,next_day_plan,productivity_score`,[userId,i.noteDate,i.workSummary??null,i.nextDayPlan??null,i.productivityScore??null])).rows[0]!;}
  static async summary(db:Pool,userId:string,start:string,end:string){return(await db.query(`SELECT COUNT(*)::int total_tasks,COUNT(*) FILTER(WHERE status='completed')::int completed_tasks,COALESCE(SUM(EXTRACT(EPOCH FROM(COALESCE(te.ended_at,NOW())-te.started_at))/60),0)::int tracked_minutes,COALESCE(ROUND(AVG(dn.productivity_score),2),0)::text average_score FROM tasks t LEFT JOIN task_time_entries te ON te.task_id=t.id LEFT JOIN daily_notes dn ON dn.user_id=t.user_id AND dn.note_date=t.task_date WHERE t.user_id=$1 AND t.task_date BETWEEN $2 AND $3`,[userId,start,end])).rows[0]!;}
}
