-- 1. SETUP & EXTENSIONS
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. COMMON UPDATED_AT TRIGGER FUNCTION
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;
